version: 2

updates:

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    reviewers: ["valispace/automations"]
    labels: ["github-actions"]
    commit-message:
      prefix: "ci(workflows)"
    ignore:
      - update-types: ["version-update:semver-major"]

  # Maintain dependencies for Docker
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
    reviewers: ["valispace/operations"]
    labels: ["docker"]
    commit-message:
      prefix: "build(docker)"
    ignore:
      - update-types: ["version-update:semver-major"]

  # Maintain dependencies for Python
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    reviewers: ["valispace/devops"]
    labels: ["dependencies", "python"]
    commit-message:
      prefix: "build(pip)"
    ignore:
      - update-types: ["version-update:semver-major"]
      - dependency-name: "pylint"
        versions: [">2.x"]  # cannot update further without breaking integration with pylint-django-2.5.3
      - dependency-name: "pyparsing"
        versions: [">2.x"]  # cannot update further without breaking integration with pint-0.21.dev0+valispace

  # Maintain dependencies for npm
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    reviewers: ["valispace/devops"]
    labels: ["dependencies", "javascript"]
    commit-message:
      prefix: "build(npm)"
    ignore:
      - update-types: ["version-update:semver-major"]
      # All base Angular packages (leaving @angular/core for the warning)
      - dependency-name: "@angular-devkit/build-angular"
      - dependency-name: "@angular/animations"
      - dependency-name: "@angular/cli"
      - dependency-name: "@angular/cdk"
      - dependency-name: "@angular/common"
      - dependency-name: "@angular/compiler"
      - dependency-name: "@angular/compiler-cli"
      - dependency-name: "@angular/forms"
      - dependency-name: "@angular/platform-browser"
      - dependency-name: "@angular/platform-browser-dynamic"
      - dependency-name: "@angular/material-moment-adapter"
      - dependency-name: "@angular/router"
      - dependency-name: "@types/jasmine"
      - dependency-name: "@types/node"
      - dependency-name: "jasmine-core"
      - dependency-name: "karma"
      - dependency-name: "karma-chrome-launcher"
      - dependency-name: "karma-coverage"
      - dependency-name: "karma-jasmine"
      - dependency-name: "karma-jasmine-html-reporter"
      - dependency-name: "rxjs"
      - dependency-name: "tslib"
      - dependency-name: "typescript"
      - dependency-name: "zone.js"
      # ESLint related packages (leaving @angular-eslint/schematics for the warning)
      - dependency-name: "@angular-eslint/builder"
      - dependency-name: "@angular-eslint/eslint-plugin"
      - dependency-name: "@angular-eslint/eslint-plugin-template"
      - dependency-name: "@angular-eslint/template-parser"
      - dependency-name: "@typescript-eslint/eslint-plugin"
      - dependency-name: "@typescript-eslint/parser"
      - dependency-name: "eslint"
