name: 'Push Docker image'
description: 'Push`s a Docker image to a Docker registry'
author: 'Valispace'
branding:
  icon: 'anchor'
  color: 'orange'
inputs:
  context:
    description: 'Build`s context is the set of files located in the specified PATH or URL'
    required: false
    default: '.'
  dockerfile:
    description: 'Path to the Dockerfile'
    required: false
    default: 'Dockerfile'
  registry:
    description: 'Server address of Docker registry (if not set it will default to GitHub Container Registry)'
    required: false
    default: 'ghcr.io'
  username:
    description: 'Username used to log against the Docker registry'
    required: false
    default: '${{ github.repository_owner }}'
  password:
    description: 'Password or personal access token used to log against the Docker registry'
    required: false
    default: '${{ github.token }}'
  logout:
    description: 'Log out from the Docker registry at the end of a job'
    required: false
    default: 'true'
  ecr:
    description: 'Specifies whether the given registry is ECR (`auto`, `true` or `false`)'
    required: false
    default: 'auto'
  labels:
    description: 'List of metadata for an image'
    required: false
    default: ''
  tags:
    description: 'List of tags'
    required: false
    default: ''
runs:
  using: composite
  steps:
    - id: login
      uses: docker/login-action@v2
      with:
        registry: '${{ inputs.registry }}'
        username: '${{ inputs.username }}'
        password: '${{ inputs.password }}'
        logout: ${{ inputs.logout }}
        ecr: '${{ inputs.ecr }}'
    - id: setup
      uses: docker/setup-buildx-action@v2
      with:
        driver: 'docker-container'
        install: true
    - id: push
      uses: docker/build-push-action@v3
      with:
        context: '${{ inputs.context }}'
        file: '${{ inputs.dockerfile }}'
        outputs: 'type=registry'
        labels: ${{ inputs.labels }}
        tags: ${{ inputs.tags }}
