name: 'Get build version'
description: 'Returns the current build version'
author: Valispace
inputs:
  file:
    description: 'Path to the versioning file'
    required: true
    default: ''
outputs:
  release:
    description: 'Current release version (e.g. xx.yy)'
    value: '${{ steps.release.outputs.version }}'
  version:
    description: 'Current build version (e.g. xx.yy.zz)'
    value: '${{ steps.build.outputs.version }}'
runs:
  using: composite
  steps:
    - id: release
      run: 'echo "version=$( echo "$( grep --extended-regexp "version" "${{ inputs.file }}" | grep --only-matching --extended-regexp "([[:digit:]]+)[.]([[:digit:]]+)" )" )" >> $GITHUB_OUTPUT'
      shell: bash
    - id: build
      run: 'echo "version=$( echo "$( grep --extended-regexp "version" "${{ inputs.file }}" | grep --only-matching --extended-regexp "([[:digit:]]+)[.]([[:digit:]]+)[.]([[:digit:]]+)" )" )" >> $GITHUB_OUTPUT'
      shell: bash
branding:
  icon: 'help-circle'
  color: 'orange'
