name: 'Upload archive to AWS S3 bucket'
description: 'Uploads the given archive to the AWS S3 bucket'
author: 'Valispace'
branding:
  icon: 'upload-cloud'
  color: 'orange'
inputs:
  archive:
    description: 'Path to the archive to upload'
    required: true
    default: ''
  aws-secret-access-key:
    description: 'The AWS Secret Access Key'
    required: true
    default: ''
  aws-access-key-id:
    description: 'The AWS Access Key ID'
    required: true
    default: ''
  aws-region:
    description: 'The AWS Region (e.g. `eu-central-1`)'
    required: false
    default: 'eu-central-1'
  aws-s3-bucket:
    description: 'The AWS S3 bucket where to upload'
    required: true
    default: ''
  aws-s3-repository:
    description: 'The AWS S3 bucket repository (the name is case insensitive) where to upload'
    required: true
    default: ''
  aws-s3-branch:
    description: 'The AWS S3 bucket branch where to upload'
    required: true
    default: ''
  aws-s3-tag:
    description: 'The AWS S3 bucket tag where to upload'
    required: false
    default: 'latest'
runs:
  using: composite
  steps:
    - id: check-required-inputs
      run: |
        if [[ "${{ inputs.archive }}" == "" ]]; then
          echo "::error title=${{ github.job }}::The path to the archive is required!" && exit 1
        fi
        if [[ "${{ inputs.aws-secret-access-key }}" == "" ]]; then
          echo "::error title=${{ github.job }}::The AWS Secret Access Key is required!" && exit 1
        fi
        if [[ "${{ inputs.aws-access-key-id }}" == "" ]]; then
          echo "::error title=${{ github.job }}::The AWS Access Key ID is required!" && exit 1
        fi
        if [[ "${{ inputs.aws-s3-bucket }}" == "" ]]; then
          echo "::error title=${{ github.job }}::The AWS S3 bucket is required!" && exit 1
        fi
        if [[ "${{ inputs.aws-s3-repository }}" == "" ]]; then
          echo "::error title=${{ github.job }}::The AWS S3 bucket repository is required!" && exit 1
        fi
        if [[ "${{ inputs.aws-s3-branch }}" == "" ]]; then
          echo "::error title=${{ github.job }}::The AWS S3 bucket branch is required!" && exit 1
        fi
      shell: bash
    - id: credentials
      uses: aws-actions/configure-aws-credentials@v1-node16
      with:
        aws-secret-access-key: '${{ inputs.aws-secret-access-key }}'
        aws-access-key-id: '${{ inputs.aws-access-key-id }}'
        aws-region: '${{ inputs.aws-region }}'
    - id: upload
      run: 'aws s3 sync . "s3://${{ inputs.aws-s3-bucket }}/${{ inputs.aws-s3-repository }}/${{ inputs.aws-s3-branch }}/${{ inputs.aws-s3-tag }}" --exclude "*" --include "${{ inputs.archive }}"'
      shell: bash
