name: 'Update ValiAdmin'
description: 'Updates ValiAdmin with the given build'
inputs:
  repository-name:
    description: 'The name of the repository (the name is not case sensitive)'
    required: true
    default: ''
  branch-name:
    description: 'The branch to update'
    required: true
    default: ''
  version:
    description: 'The build version'
    required: true
    default: ''
  valiadmin-develop-token:
    description: 'The ValiAdmin (develop) access token'
    required: false
    default: ''
  valiadmin-staging-token:
    description: 'The ValiAdmin (staging) access token'
    required: true
    default: ''
  valiadmin-master-token:
    description: 'The ValiAdmin (prod) access token'
    required: true
    default: ''
runs:
  using: composite
  steps:
    - id: data
      run: 'echo "raw={ \\\"repo\\\": \\\"${{ inputs.repository-name }}\\\", \\\"branch\\\": \\\"${{ inputs.branch-name }}\\\", \\\"build\\\": \\\"${{ inputs.version }}\\\" }" >> $GITHUB_OUTPUT'
      shell: bash
    - id: develop
      run: 'curl --request POST --header "Authorization: Token ${{ inputs.valiadmin-develop-token }}" --header "Content-Type: application/json" --data-raw "${{ steps.data.outputs.raw }}" "https://api.admin.develop.internal.valispace.com/api/branches/updateonbuild/"'
      shell: bash
    - id: staging-new
      run: 'curl --request POST --header "Authorization: Token ${{ inputs.valiadmin-staging-token }}" --header "Content-Type: application/json" --data-raw "${{ steps.data.outputs.raw }}" "https://api.admin.staging.internal.valispace.com/api/branches/updateonbuild/"'
      shell: bash
    - id: staging
      run: 'curl --request POST --header "Authorization: Token ${{ inputs.valiadmin-staging-token }}" --header "Content-Type: application/json" --data-raw "${{ steps.data.outputs.raw }}" "https://admin-staging.services.valispace.com/api/branches/updateonbuild/"'
      shell: bash
    - id: master
      run: 'curl --request POST --header "Authorization: Token ${{ inputs.valiadmin-master-token }}" --header "Content-Type: application/json" --data-raw "${{ steps.data.outputs.raw }}" "https://admin.services.valispace.com/api/branches/updateonbuild/"'
      shell: bash
