name: 'Check Spelling'
description: 'Spell check code and commits within Valispace context'
author: Valispace
inputs:
  event_aliases:
    description: 'Try to treat a GitHub event "a" as GitHub event "b" (JSON map)'
    required: false
    default: ''
  only_check_changed_files:
    description: 'If set, only check files changed since the last push'
    required: false
    default: '1'
outputs:
  unknown_words:
    description: 'Unrecognized words (should be added to expect.txt)'
    value: ${{ steps.spelling.outputs.unknown_words }}
  stale_words:
    description: 'Stale words (should be removed from expect.txt)'
    value: ${{ steps.spelling.outputs.stale_words }}
  skipped_files:
    description: 'Skipped files (could be added to excludes.txt)'
    value: ${{ steps.spelling.outputs.skipped_files }}
  suggested_dictionaries:
    description: 'Suggested dictionaries (could be added to extra_dictionaries)'
    value: ${{ steps.spelling.outputs.suggested_dictionaries }}
  warnings:
    description: 'Warnings'
    value: ${{ steps.spelling.outputs.warnings }}
  result_code:
    description: 'Result (indicates unrecognized words were found or comment needs to be collapsed)'
    value: ${{ steps.spelling.outputs.result_code }}
  followup:
    description: 'Next task'
    value: ${{ steps.spelling.outputs.followup }}
runs:
  using: composite
  steps:
    - id: spelling
      uses: check-spelling/check-spelling@v0.0.21
      with:
        event_aliases: '${{ inputs.event_aliases }}'
        only_check_changed_files: '${{ inputs.only_check_changed_files }}'
        post_comment: '0'
        config: '${{ github.action_path }}'
        extra_dictionaries:
          cspell:en_GB/src/wordsEnGb.txt
          cspell:en_GB/src/additional_words.txt
          cspell:en_US/src/en_US.txt
          cspell:en_US/src/additional_words.txt
          cspell:en_US/src/contractions-and-possessives.txt
          cspell:en_US/src/hyphenated-words.txt
          cspell:pt_PT/Portuguese-European.txt
          cspell:software-terms/src/software-terms.txt
          cspell:software-terms/src/software-tools.txt
          cspell:software-terms/src/network-protocols.txt
          cspell:software-terms/src/network-os.txt
          cspell:cryptocurrencies/cryptocurrencies.txt
          cspell:public-licenses/src/generated/public-licenses.txt
          cspell:public-licenses/src/additional-licenses.txt
          cspell:lorem-ipsum/dictionary.txt
          cspell:mnemonics/src/mnemonics.txt
          cspell:companies/src/companies.txt
          cspell:aws/aws.txt
          cspell:docker/src/docker-words.txt
          cspell:bash/bash-words.txt
          cspell:fullstack/fullstack.txt
          cspell:django/django.txt
          cspell:django/requirements.txt
          cspell:node/additional_words.txt
          cspell:node/node.txt
          cspell:node/src/node-old.txt
          cspell:npm/npm.txt
          cspell:python/src/python/python.txt
          cspell:python/src/python/python-lib.txt
          cspell:python/src/common/extra.txt
          cspell:python/src/additional_words.txt
          cspell:typescript/typescript.txt
          cspell:html/html.txt
          cspell:html-symbol-entities/entities.txt
          cspell:css/css.txt
          cspell:fonts/fonts.txt
          cspell:filetypes/filetypes.txt
branding:
  icon: 'edit-3'
  color: 'orange'
