name: 'Sync Branches'
description: 'Creates a branch and opens a PR with target branch'
inputs:
  github-token:
    description: 'Github Token'
    required: true
    default: ''
  to-branch:
    description: 'The name of the branch where the PR will merge to'
    required: true
    default: ''
  temp-branch:
    description: 'The name of the branch to be created'
    required: true
    default: ''
  pr-author-id:
    description: 'The id of the PR Autor'
    required: true
    default: ''
  files:
    description: 'List of files to be merged from the source branch'
    required: true

runs:
  using: "composite"
  steps:

  - name: Checkout
    uses: actions/checkout@v2

  - name: Set up Node
    uses: actions/setup-node@v1
    with:
      node-version: 12

  - name: Create Branch
    shell: bash
    run: git checkout -b ${{ inputs.temp-branch}}

  - name: Merge specific files from source branch
    shell: bash
    run: |
      git fetch origin ${{ inputs.to-branch }}:${{ inputs.to-branch }}
      git config --local user.email "actions@github.com"
      git config --local user.name "GitHub Actions"
      IFS=',' read -ra FILES <<< "${{ inputs.files }}"
      for file in "${FILES[@]}"; do
        git checkout ${{ inputs.to-branch }} -- $file
        git add $file
      done
      git commit -m "Merged specific files from source branch"
      git push --set-upstream origin ${{ inputs.temp-branch }}

  - name: Opening pull request
    id: pull
    uses: tretuna/sync-branches@1.4.0
    with:
      GITHUB_TOKEN: ${{ inputs.github-token }}
      FROM_BRANCH: ${{ inputs.temp-branch }}
      TO_BRANCH: ${{ inputs.to-branch }}
      REVIEWERS: [pr-author-id]