name: 'Build Docker image'
description: 'Builds a Docker image with Buildx'
author: 'Valispace'
branding:
  icon: 'anchor'
  color: 'orange'
inputs:
  context:
    description: 'Build`s context is the set of files located in the specified PATH or URL'
    required: false
    default: '.'
  dockerfile:
    description: 'Path to the Dockerfile'
    required: false
    default: 'Dockerfile'
  archive-name:
    description: 'Docker image specification tarball name (e.g. `valispace-docker.tar.gz`)'
    required: false
    default: ''
  labels:
    description: 'List of metadata for an image'
    required: false
    default: ''
  tags:
    description: 'List of tags'
    required: false
    default: 'latest'
outputs:
  image-id:
    description: 'Image ID'
    value: '${{ steps.build.imageid }}'
  digest:
    description: 'Image digest'
    value: '${{ steps.build.digest }}'
  metadata:
    description: 'Build result metadata'
    value: '${{ steps.build.metadata }}'
runs:
  using: composite
  steps:
    - id: setup
      uses: docker/setup-buildx-action@v2
      with:
        driver: 'docker-container'
        install: true
    - id: build
      uses: docker/build-push-action@v3
      with:
        context: '${{ inputs.context }}'
        file: '${{ inputs.dockerfile }}'
        outputs: 'type=docker,dest=${{ inputs.archive-name }}'
        labels: ${{ inputs.labels }}
        tags: ${{ inputs.tags }}
