name: 'Build Notifier'
description: 'Send build notifications for a Github Action executed'

inputs:
  slack-webhook-url:
    description: 'Slack Webhook URL to send build notifications'
    required: true
    default: ''
  github-server-url:
    description: 'Github server URL'
    required: true
    default: ''
  github-owner:
    description: 'Github owner'
    required: true
    default: ''
  github-repo:
    description: 'Github repository'
    required: true
    default: ''
  app-version:
    description: 'The version of the application'
    required: true
    default: ''
  github-branch:
    description: 'The branch of the repository'
    required: true
    default: ''
  github-trigger:
    description: 'The trigger of the build'
    required: true
    default: ''
  github-sha:
    description: 'The commit SHA'
    required: true
    default: ''
  notification-type:
    description: 'The type of notification'
    required: true
    default: 'build'

runs:
  using: composite
  steps:
    - name: 'Notify channel #${{ steps.sanitize.outputs.channel }}'
      id: notify
      if: ${{ inputs.notification-type == 'build' }} && ${{ success() || failure() || cancelled() }}
      uses: adamkdean/simple-slack-notify@v1.1.2
      env:
        SLACK_WEBHOOK_URL: '${{ inputs.slack-webhook-url }}'
      with:
        channel: '#${{ steps.sanitize.outputs.channel }}'
        status: '${{ job.status }}'
        success_text:   '  [*SUCCESS*] <${{ inputs.github-server-url }}/${{ inputs.github-owner }}/${{ inputs.github-repo }}/actions/runs/${{ github.run_id }}|${{ github.workflow }} (${{ inputs.github-repo }} - ${{ inputs.app-version }})>'
        failure_text:   '  [*FAILURE*] <${{ inputs.github-server-url }}/${{ inputs.github-owner }}/${{ inputs.github-repo }}/actions/runs/${{ github.run_id }}|${{ github.workflow }} (${{ inputs.github-repo }} - ${{ inputs.app-version }})>'
        cancelled_text: '[*CANCELLED*] <${{ inputs.github-server-url }}/${{ inputs.github-owner }}/${{ inputs.github-repo }}/actions/runs/${{ github.run_id }}|${{ github.workflow }} (${{ inputs.github-repo }} - ${{ inputs.app-version }})>'
        fields: |
          [
            { "title": "Trigger", "value": "<${{ inputs.github-server-url }}/${{ inputs.github-owner }}/${{ inputs.github-repo }}/commit/${{ inputs.github-sha }}|${{ inputs.github-branch }}> - ${{ inputs.github-trigger }}", "short": false }
          ]