name: 'Build Notifier'
description: 'Send build notifications for a Github Action executed'

inputs:
  slack-webhook-url:
    description: 'Slack Webhook URL to send build notifications'
    required: true
    default: ''

runs:
  using: composite
  steps:
  #   ---- NOTIFICATIONS ----
    - name: 'Notify channel #${{ steps.sanitize.outputs.channel }}'
      id: notify
      if: ${{ always() }}
      uses: adamkdean/simple-slack-notify@v1.1.2
      env:
        SLACK_WEBHOOK_URL: '${{ secrets.SLACK_WEBHOOK_URL }}'
      with:
        channel: '#${{ steps.sanitize.outputs.channel }}'
        status: '${{ job.status }}'
        success_text:   '  [*SUCCESS*] <${{ github.server_url }}/${{ steps.sanitize.outputs.owner }}/${{ steps.sanitize.outputs.repo }}/actions/runs/${{ github.run_id }}|${{ github.workflow }} (${{ steps.sanitize.outputs.repo }} - ${{ steps.bump.outputs.version }})>'
        failure_text:   '  [*FAILURE*] <${{ github.server_url }}/${{ steps.sanitize.outputs.owner }}/${{ steps.sanitize.outputs.repo }}/actions/runs/${{ github.run_id }}|${{ github.workflow }} (${{ steps.sanitize.outputs.repo }} - ${{ steps.bump.outputs.version }})>'
        cancelled_text: '[*CANCELLED*] <${{ github.server_url }}/${{ steps.sanitize.outputs.owner }}/${{ steps.sanitize.outputs.repo }}/actions/runs/${{ github.run_id }}|${{ github.workflow }} (${{ steps.sanitize.outputs.repo }} - ${{ steps.bump.outputs.version }})>'
        fields: |
          [
            { "title": "Trigger", "value": "<${{ github.server_url }}/${{ steps.sanitize.outputs.owner }}/${{ steps.sanitize.outputs.repo }}/commit/${{ github.sha }}|${{ steps.sanitize.outputs.branch }}> - ${{ steps.sanitize.outputs.trigger }}", "short": false }
          ]